task_prompts = dict(
    
    tictactoe="Tic Tac Toe is a game played on a 3x3 grid where players take turns placing X or O in the cells. The goal is to form a horizontal, vertical, or diagonal line with three of your own marks. In this matrix, an empty cell should be represented by -1, X should be represented by 1, and O should be represented by 0. For example,\nGame State: [[-1, -1, -1], [-1, -1, -1], [-1, -1, -1]]\nrepresents an empty board. Based on the current board state matrix, think step-by-step and please answer the following question where answer should be one of A, B, C, or D.",
    
    sudoku="Sudoku is a logic-based puzzle played on a 9x9 grid, subdivided into nine 3x3 subgrids. The goal is to fill the grid so that each row, column, and 3x3 subgrid contains all digits from 1 to 9 without repetition. The grid starts with some cells filled with numbers (clues), and you must fill in the remaining empty cells one at a time. Rows are labeled A to I (top to bottom), and columns are numbered 1 to 9 (left to right). Each move involves placing a digit (1-9) in an empty cell, ensuring no repetition in its row, column, or 3x3 subgrid. For example, \"A1 5\" places 5 in the top-left cell. Based on the current board state matrix, think step-by-step and please answer the following question where answer should be one of A, B, C, or D.",
    
    reversi="Reversi (also known as Othello) is a strategy board game played on an 8x8 grid, where two players take turns placing black and white pieces on the board. The goal is to have more pieces of your color on the board than your opponent by the end of the game. A piece is placed on an empty square and must sandwich one or more of the opponent's pieces between the newly placed piece and another of the player's pieces in a horizontal, vertical, or diagonal line. The opponent's pieces in between are then flipped to the player's color. In this matrix, empty cells should be represented by 0, black pieces by 1, and white pieces by 2. For example,\nGame State: [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 2, 1, 0, 0, 0], [0, 0, 0, 1, 2, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]\n represents a Reversi board with the initial four pieces placed. Based on the provided matrix representation of the current game state, think step-by-step and please answer the following question where answer should be one of A, B, C, or D.",
    
    minesweeper="Minesweeper is a logic-based puzzle game played on an 8x8 grid with exactly 10 mines. Each cell can either contain a mine (represented by 9), or it can be empty. Unrevealed cells should be represented by -1. Cells that are revealed and contain no adjacent mines are represented by 0, while cells that are revealed and show a number from 1 to 8 indicate how many adjacent mines surround the cell. Mines are represented by the number 9. \nFor example,\nGame State: [[-1, 1, 1, 2, -1, -1, -1, 1], [1, 2, 3, 2, -1, 1, 1, 2], [2, 3, 4, 3, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2, 2, 1], [1, 2, 2, 2, 2, 9, 1, 0], [-1, 1, 2, 3, 2, 1, 0, -1], [-1, -1, 1, 2, 3, 1, -1, -1], [1, 2, 9, 1, 1, -1, -1, -1]]\nThis example represents a grid where some cells have been uncovered, showing numbers indicating adjacent mines, unrevealed cells are represented by -1, and mines are represented by the number 9. Based on the provided matrix representation of the current game state, think step-by-step and please answer the following question where answer should be one of A, B, C, or D.",
    
    gomoku="Gomoku is a game played on a 15x15 grid where players take turns placing black or white stones on the intersections. In this matrix, an empty intersection should be represented by 0, a black stone by 1, and a white stone by 2. For example,\nGame State: [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]\nrepresents a partially filled Gomoku board. Gomoku is played on a 15x15 grid, where black and white stones are placed in turns. The goal is to place five consecutive stones in a horizontal, vertical, or diagonal line. Based on the provided matrix representation of the current game state, think step-by-step and please answer the following question where answer should be one of A, B, C, or D.",
    
    chess="Chess is a strategy game played on an 8x8 board with 64 squares, using six types of pieces: pawns, knights, bishops, rooks, queens, and kings, for both white and black players. Each type of chess piece, both black and white, is represented by a unique number:\n- Empty squares: 0\n- White pieces: Pawn=1, Knight=2, Bishop=3, Rook=4, Queen=5, King=6\n- Black pieces: Pawn=-1, Knight=-2, Bishop=-3, Rook=-4, Queen=-5, King=-6\n\nFor example, the initial chess position would be represented as:\nGame State: [[-4, -2, -3, -5, -6, -3, -2, -4], [-1, -1, -1, -1, -1, -1, -1, -1], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1], [4, 2, 3, 5, 6, 3, 2, 4]]\n\nThe board uses a coordinate system where columns are labeled \"a\" through \"h\" from left to right, and rows are labeled \"1\" through \"8\" from bottom to top (a1 at bottom-left, h8 at top-right). Based on the provided matrix representation of the current game state, think step-by-step and please answer the following question where answer should be one of A, B, C, or D."
)